apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-app-8-backend
    helios.io/managed-by: operator
  name: test-app-8-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app-8-backend
  template:
    metadata:
      labels:
        app: test-app-8-backend
    spec:
      containers:
      - env:
        - name: NODE_ENV
          value: production
        image: phamhoangkha1403/test-app-8-service:latest
        name: test-app-8-backend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app-8-backend
  name: test-app-8-backend
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: test-app-8-backend
  type: ClusterIP
